---
title: "Colorado Court Watch Report"
author: "QJL"
date: "1/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, fig.width = 12)
library(tidyverse)
library(table1)
library(knitr)
library(kableExtra)

setwd("/Volumes/GoogleDrive/My Drive/QJL/ACLU Court Watch") 
cw = read_csv("courtwatch_clean.csv")

```


# Dataset Descriptives
```{r descriptors}

table1data <-
cw %>% 
  select(
  WhichCourt,
  DefRace,
  DefGender,
  DefEstimatedAge,
  DefRepByCounsel,
  ChargesCategorized,
  Assault.Violent.DV,
  Drug.Related,
  ProsCashBail,
  CashBailSet,
#  CourtWatchername,
#  Judgeslastname,
  CaseResolved,
  Result
#  DefenseBondRequest,
#  ProsecutionBondRequest,
#  Bondsetbycourt
) %>%
  mutate(
    WhichCourt = fct_explicit_na(WhichCourt),
    Drug.Related = fct_explicit_na( fct_recode(as.factor(Drug.Related), "Yes" = "1", "No" = "0" )) ,
    Assault.Violent.DV = fct_explicit_na( fct_recode(as.factor(Assault.Violent.DV), "Yes" = "1", "No" = "0" )) ,
    DefRepByCounsel = fct_explicit_na( fct_recode(as.factor(DefRepByCounsel), "Yes" = "1", "No" = "0" )) ,
    CashBailSet = fct_explicit_na( fct_recode(as.factor(CashBailSet), "Yes" = "1", "No" = "0" )) ,
    ProsCashBail = fct_explicit_na( fct_recode(as.factor(ProsCashBail), "Yes" = "1", "No" = "0" ) ),
    CaseResolved =  fct_explicit_na(   fct_recode(as.factor(CaseResolved), "Yes" = "1", "No" = "0" )),
    Result = fct_explicit_na(Result),
    ChargesCategorized = fct_explicit_na(ChargesCategorized)
)

label(table1data$DefRace) <- "Defendant Race"
label(table1data$DefGender) <- "Defendant Gender"
label(table1data$DefEstimatedAge) <- "Defendant Estimated Age"
label(table1data$DefRepByCounsel) <- "Defendant Represented by Counsel"
label(table1data$ChargesCategorized) <- "Primary Charge"
label(table1data$Assault.Violent.DV) <- "Violent Crime, Assault, or DV"
label(table1data$Drug.Related) <- "Drug Related"
label(table1data$CashBailSet) <- "Cash Bail Set"
label(table1data$CaseResolved) <- "Case Resolved"
label(table1data$ProsCashBail) <- "Prosecution Requests Cash Bail"


table1(~ DefRace + DefGender + DefEstimatedAge + DefRepByCounsel + ChargesCategorized + Assault.Violent.DV + Drug.Related + ProsCashBail + CashBailSet + CaseResolved + Result | WhichCourt, data = table1data)
```


# What Offenses Are Charged By What Courts?

```{r chargecounts, echo=FALSE}



cw %>%  
  group_by( WhichCourt, ChargesCategorized) %>%
  summarize(count= n()) %>%
  filter(is.na(WhichCourt) == FALSE) %>%
  ggplot( aes(x = reorder(ChargesCategorized, count), y = count, fill = reorder(ChargesCategorized, count))) + 
  geom_bar(stat = "identity", position = "dodge", alpha = .8, color = "black") +
  
  ggtitle('Offenses Charged by Court (Counts)') +
  theme(
    plot.title = element_text( face="bold", hjust = 0.5 ),
    legend.title = element_text(),
    legend.position = "none",
    axis.title.x = element_text(vjust=-2),
    axis.title.y = element_text(vjust= 2),
    axis.text.x=element_text(angle = 90),

    axis.ticks.x = element_blank()
    
  )+ 
  scale_y_continuous(labels = function(x) paste0(round(x)), expand = c(0, 0 ), limits = c(-1, 450)) +
  geom_text(aes(label= paste0(round(count)), y = count+20), position = position_dodge(width = .9), size = 4 ) +
  labs(x="Court", y="Number Charges", fill = "Charge Type")  +
  coord_cartesian(clip = 'off')+
  scale_fill_brewer(palette="Set1") +
  facet_wrap(~WhichCourt)


```
<br>
<br>
```{r chargedistributions, echo=FALSE, fig.width = 12}

cw %>%  
  group_by( WhichCourt) %>%
  add_tally() %>%
  group_by( WhichCourt, n, ChargesCategorized) %>%
  summarize(count= n()) %>%
  ungroup() %>%
  mutate(percent = count/n*100) %>%
  mutate(labelq = ifelse(ChargesCategorized == "Other", paste0(n, " Cases Charged"), "")
         ) %>%
  filter(is.na(WhichCourt) == FALSE, is.na(ChargesCategorized) == FALSE) %>%
  
  ggplot( aes(x = reorder(WhichCourt, percent), y = percent, fill = reorder(ChargesCategorized, percent))) + 
  geom_bar(stat = "identity", position = "dodge", alpha = .8, color = "black") +
  
  ggtitle('Percent of Offenses by Charge and Court') +
  theme(
    plot.title = element_text( face="bold", hjust = 0.5 ),
    legend.title = element_text(),
  #  legend.position = 
    axis.title.x = element_text(vjust=-2),
    axis.title.y = element_text(vjust= 2),
    axis.text.x=element_text(vjust=-3),
    axis.ticks.x = element_blank()
    
  )+ 
  scale_y_continuous(labels = function(x) paste0(round(x), "%"), expand = c(0, 0 ), limits = c(-1, 45)) +
  geom_text(aes(label= paste0(round(percent), "%"), y = percent+1), position = position_dodge(width = .9), size = 3  ) +
  geom_text(aes(label= paste0(labelq ),  y = 0), vjust = 2.5, size = 3 ) +
  labs(x="Court", y="Offenses Charged, %", fill = "Offenses")  +
  coord_cartesian(clip = 'off')+
  scale_fill_brewer(palette="Set1")

```
<br>
<br>


# Use of PR Bonds
```{r prbonds}

cw %>%  
  group_by(WhichCourt) %>%
  add_tally() %>%
  group_by( WhichCourt, n, Bondsetbycourt) %>%
  summarize(count= n()) %>%
  ungroup() %>%
  mutate(percent = count/n*100) %>%
  spread(Bondsetbycourt, percent, fill = 0) %>%
  group_by(WhichCourt, n) %>% 
  summarize( percent = sum(`Personal Recognizance (PR)`)) %>%
  mutate(pr_count = percent * n/100) %>%
  filter(is.na(WhichCourt) == FALSE) %>%
  
  ggplot( aes(x = reorder(WhichCourt, percent), y = percent) )+ 
  geom_bar(stat = "identity", position = "dodge", alpha = .8, color = "black") +
  
  ggtitle('Use of Personal Recognizance (PR) Bonds, %') +
  theme(
    plot.title = element_text( face="bold", hjust = 0.5 ),
    legend.title = element_text(),
  #  legend.position = 
    axis.title.x = element_text(vjust=-2),
    axis.title.y = element_text(vjust= 2),
    axis.text.x=element_text(vjust=-3),
    axis.ticks.x = element_blank()
    
  )+ 
  scale_y_continuous(labels = function(x) paste0(round(x), "%"), expand = c(0, 0 ), limits = c(-1, 75)) +
  geom_text(aes(label= paste0(round(percent), "%", " ", pr_count, " Cases"), y = percent+2), position = position_dodge(width = .9), size = 3  ) +
  geom_text(aes(label= paste0(n, " Cases in Court"),  y = 0), vjust = 2, size = 3 ) +
  labs(x="Court", y="PR Bonds, %")  +
  coord_cartesian(clip = 'off')+
  scale_fill_brewer(palette="Set1")

```

